GET https://jsonplaceholder.typicode.com/posts

###
POST https://jsonplaceholder.typicode.com/posts
Content-Type: application/json

{
    "title":"My Post",
    "body": "This is my post"
}
###
POST http://localhost:3000/links
Content-Type: application/json

{
    "title":"My Post",
    "body": "This is my post"
}